// apps/crawler/src/scripts/ops/production-smoke/constants.ts
// 定義 production smoke CLI flag、預設門檻與跨檢查共用的時間換算常數。

export const HELP_FLAG = "--help";
export const PUBLIC_ONLY_FLAG = "--public-only";
export const DEFAULT_BASE_URL = "http://127.0.0.1:3000";
export const DEFAULT_TIMEOUT_MS = 5000;
export const DEFAULT_PRODUCT_IMAGE_STORAGE_DIR = "storage/product-images";
export const DEFAULT_PRODUCT_IMAGE_SAMPLE_SIZE = 5;
export const DEFAULT_SOURCE_WARN_AFTER_MINUTES = 60;
export const DEFAULT_SOURCE_FAIL_AFTER_MINUTES = 120;
export const DEFAULT_CRAWLER_WARN_AFTER_MINUTES = 90;
export const DEFAULT_CRAWLER_FAIL_AFTER_MINUTES = 180;
export const DEFAULT_RECENT_WINDOW_HOURS = 24;
export const DEFAULT_PARSE_ERROR_WARN_COUNT = 20;
export const DEFAULT_PARSE_ERROR_FAIL_COUNT = 100;
export const DEFAULT_SOURCE_IMAGE_FAILURE_MIN_CONSECUTIVE = 3;
export const DEFAULT_SOURCE_IMAGE_FAILURE_WARN_COUNT = 100;
export const DEFAULT_SOURCE_IMAGE_FAILURE_FAIL_COUNT = 300;
export const DEFAULT_MIN_ACTIVE_PRODUCTS = 1;
export const DEFAULT_FILTER_EMPTY_WARN_MIN_COUNT = 10;
export const DEFAULT_FILTER_EMPTY_WARN_RATIO = 0.005;
export const DEFAULT_MISSING_IMAGE_WARN_COUNT = 30;
export const DEFAULT_MISSING_IMAGE_FAIL_COUNT = 100;
export const DEFAULT_RAW_SNAPSHOT_NORMAL_RETENTION_DAYS = 30;
export const DEFAULT_RAW_SNAPSHOT_ABNORMAL_RETENTION_DAYS = 90;
export const DEFAULT_RAW_SNAPSHOT_RETENTION_GRACE_DAYS = 2;
export const DEFAULT_RAW_SNAPSHOT_WARN_COUNT = 1;
export const DEFAULT_RAW_SNAPSHOT_FAIL_COUNT = 100;
export const MILLISECONDS_PER_MINUTE = 60 * 1000;
export const MILLISECONDS_PER_HOUR = 60 * MILLISECONDS_PER_MINUTE;
export const MILLISECONDS_PER_DAY = 24 * MILLISECONDS_PER_HOUR;
