// apps/web/tests/repo-path-comment-policy.test.ts
import { readdir, readFile } from "node:fs/promises";
import { join, relative, resolve, sep } from "node:path";
import { describe, expect, it } from "vitest";

const REPOSITORY_ROOT = resolve(__dirname, "../../..");
const POLICY_ROOTS = ["apps", "packages"];
const SOURCE_EXTENSIONS = new Set([".ts", ".tsx", ".css"]);
const DIRECTIVE_LINES = new Set(['"use client";', '"use server";']);
const IGNORED_DIRECTORY_NAMES = new Set([
  ".next",
  "build",
  "coverage",
  "dist",
  "fixtures",
  "node_modules",
  "out",
]);
const IGNORED_RELATIVE_PATHS = new Set([
  // Generated by Next.js; editing it would be overwritten by the framework.
  "apps/web/next-env.d.ts",
]);

describe("repo path comment policy", () => {
  it("keeps repo-relative path comments on apps and packages source files", async () => {
    const files = await collectPolicySourceFiles();
    const filesWithMissingPathComment: string[] = [];

    for (const file of files) {
      const relativePath = toRepoRelativePath(file);
      const source = await readFile(file, "utf8");

      if (!hasExpectedPathComment(relativePath, source)) {
        filesWithMissingPathComment.push(relativePath);
      }
    }

    expect(filesWithMissingPathComment).toEqual([]);
  });
});

async function collectPolicySourceFiles(): Promise<string[]> {
  const files: string[] = [];

  for (const root of POLICY_ROOTS) {
    files.push(...(await collectSourceFiles(join(REPOSITORY_ROOT, root))));
  }

  return files;
}

async function collectSourceFiles(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const path = join(root, entry.name);

    if (entry.isDirectory()) {
      if (!IGNORED_DIRECTORY_NAMES.has(entry.name)) {
        files.push(...(await collectSourceFiles(path)));
      }

      continue;
    }

    if (!entry.isFile()) {
      continue;
    }

    const relativePath = toRepoRelativePath(path);

    if (IGNORED_RELATIVE_PATHS.has(relativePath)) {
      continue;
    }

    if (SOURCE_EXTENSIONS.has(getExtension(entry.name))) {
      files.push(path);
    }
  }

  return files;
}

function hasExpectedPathComment(relativePath: string, source: string): boolean {
  const lines = source.split(/\r?\n/);
  const expectedComment = relativePath.endsWith(".css")
    ? `/* ${relativePath} */`
    : `// ${relativePath}`;

  if (lines[0] === expectedComment) {
    return true;
  }

  return DIRECTIVE_LINES.has(lines[0] ?? "") && lines[1] === expectedComment;
}

function toRepoRelativePath(path: string): string {
  return relative(REPOSITORY_ROOT, path).split(sep).join("/");
}

function getExtension(fileName: string): string {
  if (fileName.endsWith(".tsx")) {
    return ".tsx";
  }

  if (fileName.endsWith(".css")) {
    return ".css";
  }

  return fileName.endsWith(".ts") ? ".ts" : "";
}
