// apps/crawler/src/scripts/manual/validate-coolpc-live/report.ts
// 產生 CoolPC 手動驗證流程的回報資料。
// 負責將 parser 驗證結果轉成可閱讀的報表與 issue 統計。

import type { CoolpcTargetCategory } from "../../../coolpc/categories";
import type {
  CoolpcParseIssue,
  ParsedCoolpcProduct,
  SourceCategoryContext,
} from "../../../coolpc/parser";

// 驗證回報的一列摘要資料，供報表輸出與可讀性檢查使用。
export interface ValidationSummary {
  igrp: number;
  displayName: string;
  url: string;
  fetchedAt: string;
  httpStatus: number;
  validationStatus: string;
  validationReason: string | null;
  title: string;
  tokenCount: number;
  nameCount: number;
  priceTextCount: number;
  parsedItemCount: number;
  deduplicatedItemCount: number;
  issueCounts: Record<string, number>;
  canImport: boolean;
  firstItems: Array<Pick<ParsedCoolpcProduct, "name" | "price" | "sourceItemKey">>;
}

export function createContext(
  category: CoolpcTargetCategory,
  fetchedAt: Date,
  sourceCategoryUrl: string,
): SourceCategoryContext {
  return {
    sourceCategoryId: `manual-coolpc-igrp-${category.igrp}`,
    igrp: category.igrp,
    sourceName: category.sourceName,
    displayName: category.displayName,
    fetchedAt,
    sourceCategoryUrl,
    expectedTitleKeywords: category.expectedTitleKeywords
      ? [...category.expectedTitleKeywords]
      : undefined,
  };
}

// 將每個分類的驗證結果整理為 Markdown 報表，並註明是否為 raw 重放模式。
export function createMarkdownReport(
  summaries: ValidationSummary[],
  outputDir: string,
  inputRawDir: string | null,
): string {
  const rows = summaries
    .map(
      (summary) =>
        `| ${summary.displayName} | ${summary.igrp} | ${summary.httpStatus} | ${summary.validationStatus} | ${summary.validationReason ?? ""} | ${summary.tokenCount} | ${summary.nameCount} | ${summary.priceTextCount} | ${summary.parsedItemCount} | ${summary.deduplicatedItemCount} | ${summary.canImport ? "yes" : "no"} |`,
    )
    .join("\n");
  const issueSections = summaries
    .map((summary) => {
      const issues =
        Object.entries(summary.issueCounts)
          .map(([type, count]) => `  - ${type}: ${count}`)
          .join("\n") || "  - none";
      const firstItems =
        summary.firstItems
          .map(
            (item) =>
              `  - ${item.sourceItemKey} | ${item.price} | ${sanitizeMarkdownCell(item.name)}`,
          )
          .join("\n") || "  - none";

      return `### ${summary.displayName} (IGrp=${summary.igrp})

- Title: ${summary.title}
- URL: ${summary.url}
- Fetched at: ${summary.fetchedAt}
- Issues:
${issues}
- First parsed items:
${firstItems}
`;
    })
    .join("\n");

  const runModeLines = inputRawDir
    ? `- Input raw directory: \`${inputRawDir}\`
- This run replays saved raw HTML and does not perform live requests.`
    : "- This run performs live requests and is not part of regular automated tests.";

  return `# CoolPC Parser Validation

This report was generated by the manual-only crawler validation command.

- Output directory: \`${outputDir}\`
${runModeLines}
- Full raw HTML was written under the output directory, which is ignored by git.

| Category | IGrp | HTTP | Validation | Reason | div.w | div.t | div.x | Parsed | Deduped | Import |
| --- | ---: | ---: | --- | --- | ---: | ---: | ---: | ---: | ---: | --- |
${rows}

${issueSections}
`;
}

// 將解析議題依類型彙總，供報表 issue 區塊輸出。
export function countIssues(issues: CoolpcParseIssue[]): Record<string, number> {
  return issues.reduce<Record<string, number>>((counts, issue) => {
    counts[issue.type] = (counts[issue.type] ?? 0) + 1;
    return counts;
  }, {});
}

// 清理 Markdown 表格欄位值，避免 `|` 被當成欄位分隔符號。
function sanitizeMarkdownCell(value: string): string {
  return value.replaceAll("|", "\\|").replace(/\s+/g, " ").trim();
}
