// apps/crawler/src/scripts/manual/validate-coolpc-live/report.ts

import type { CoolpcTargetCategory } from "../../../coolpc/categories";
import type {
  CoolpcParseIssue,
  ParsedCoolpcProduct,
  SourceCategoryContext,
} from "../../../coolpc/parser";

export interface ValidationSummary {
  igrp: number;
  displayName: string;
  sourceName: string;
  url: string;
  fetchedAt: string;
  httpStatus: number;
  byteLength: number;
  validationStatus: string;
  validationReason: string | null;
  title: string;
  tokenCount: number;
  nameCount: number;
  priceTextCount: number;
  validCandidateCount: number;
  parsedItemCount: number;
  deduplicatedItemCount: number;
  issueCounts: Record<string, number>;
  canImport: boolean;
  firstItems: Array<
    Pick<ParsedCoolpcProduct, "ibuyToken" | "name" | "primaryImageUrl" | "price" | "sourceItemKey">
  >;
}

export function createContext(
  category: CoolpcTargetCategory,
  fetchedAt: Date,
  sourceCategoryUrl: string,
): SourceCategoryContext {
  return {
    sourceCategoryId: `manual-coolpc-igrp-${category.igrp}`,
    igrp: category.igrp,
    sourceName: category.sourceName,
    displayName: category.displayName,
    fetchedAt,
    sourceCategoryUrl,
    expectedTitleKeywords: category.expectedTitleKeywords
      ? [...category.expectedTitleKeywords]
      : undefined,
  };
}

export function createSampleFixture(
  category: CoolpcTargetCategory,
  fetchedAt: Date,
  items: ParsedCoolpcProduct[],
): string {
  const rows = items
    .map(
      (item) => `      <div class="item">
        <div class="w">${escapeHtml(item.ibuyToken)}</div>
        <span>
          <img src="${escapeHtml(item.primaryImageUrl ?? "")}" alt="${escapeHtml(item.name)}">
          <div class="t">${escapeHtml(item.name)}</div>
          <div class="x">含稅：NT${formatPrice(item.price)}</div>
        </span>
      </div>`,
    )
    .join("\n");

  return `<!--
Fixture: sampled live CoolPC ${category.displayName} category structure.
Source type: eachview.php?IGrp=${category.igrp} category page.
Fixture date: ${fetchedAt.toISOString().slice(0, 10)}.
This fixture is reduced from a manual live validation run and keeps only parser-relevant structure.
-->
<!doctype html>
<html lang="zh-Hant-TW">
  <head>
    <title>原價屋${escapeHtml(category.sourceName)}總覽</title>
  </head>
  <body>
    <section class="category">
${rows}
    </section>
  </body>
</html>
`;
}

export function createMarkdownReport(
  summaries: ValidationSummary[],
  outputDir: string,
  inputRawDir: string | null,
): string {
  const rows = summaries
    .map(
      (summary) =>
        `| ${summary.displayName} | ${summary.igrp} | ${summary.httpStatus} | ${summary.validationStatus} | ${summary.validationReason ?? ""} | ${summary.tokenCount} | ${summary.nameCount} | ${summary.priceTextCount} | ${summary.parsedItemCount} | ${summary.deduplicatedItemCount} | ${summary.canImport ? "yes" : "no"} |`,
    )
    .join("\n");
  const issueSections = summaries
    .map((summary) => {
      const issues =
        Object.entries(summary.issueCounts)
          .map(([type, count]) => `  - ${type}: ${count}`)
          .join("\n") || "  - none";
      const firstItems =
        summary.firstItems
          .map(
            (item) =>
              `  - ${item.sourceItemKey} | ${item.price} | ${sanitizeMarkdownCell(item.name)}`,
          )
          .join("\n") || "  - none";

      return `### ${summary.displayName} (IGrp=${summary.igrp})

- Title: ${summary.title}
- URL: ${summary.url}
- Fetched at: ${summary.fetchedAt}
- Issues:
${issues}
- First parsed items:
${firstItems}
`;
    })
    .join("\n");

  const runModeLines = inputRawDir
    ? `- Input raw directory: \`${inputRawDir}\`
- This run replays saved raw HTML and does not perform live requests.`
    : "- This run performs live requests and is not part of regular automated tests.";

  return `# CoolPC Parser Validation

This report was generated by the manual-only crawler validation command.

- Output directory: \`${outputDir}\`
${runModeLines}
- Full raw HTML was written under the output directory, which is ignored by git.

| Category | IGrp | HTTP | Validation | Reason | div.w | div.t | div.x | Parsed | Deduped | Import |
| --- | ---: | ---: | --- | --- | ---: | ---: | ---: | ---: | ---: | --- |
${rows}

${issueSections}
`;
}

export function countIssues(issues: CoolpcParseIssue[]): Record<string, number> {
  return issues.reduce<Record<string, number>>((counts, issue) => {
    counts[issue.type] = (counts[issue.type] ?? 0) + 1;
    return counts;
  }, {});
}

function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-US").format(price);
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function sanitizeMarkdownCell(value: string): string {
  return value.replaceAll("|", "\\|").replace(/\s+/g, " ").trim();
}
